export const PROVINCES = [
  "Buenos Aires",
  "Ciudad Autónoma de Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

export const LOCALITIES: Record<string, string[]> = {
  "Buenos Aires": [
    "Adolfo Alsina", "Adolfo Gonzales Chaves", "Alberti", "Almirante Brown", "Arrecifes",
    "Avellaneda", "Ayacucho", "Azul", "Bahía Blanca", "Balcarce", "Baradero", "Berazategui",
    "Berisso", "Bolívar", "Bragado", "Brandsen", "Campana", "Cañuelas", "Capitán Sarmiento",
    "Carlos Casares", "Carlos Tejedor", "Carmen de Areco", "Castelli", "Chacabuco", "Chascomús",
    "Chivilcoy", "Colón", "Coronel Dorrego", "Coronel Pringles", "Coronel Rosales",
    "Coronel Suárez", "Daireaux", "Dolores", "Ensenada", "Escobar", "Esteban Echeverría",
    "Exaltación de la Cruz", "Ezeiza", "Florencio Varela", "Florentino Ameghino",
    "General Alvarado", "General Alvear", "General Arenales", "General Belgrano",
    "General Guido", "General Juan Madariaga", "General La Madrid", "General Las Heras",
    "General Lavalle", "General Paz", "General Pinto", "General Pueyrredón",
    "General Rodríguez", "General San Martín", "General Sarmiento", "General Viamonte",
    "General Villegas", "Guaminí", "Hurlingham", "Ituzaingó", "José C. Paz",
    "Junín", "La Costa", "La Matanza", "La Plata", "Lanús", "Laprida",
    "Las Flores", "Leandro N. Alem", "Lincoln", "Lobería", "Lobos", "Lomas de Zamora",
    "Luján", "Magdalena", "Maipú", "Malvinas Argentinas", "Mar Chiquita", "Mar del Plata",
    "Marcos Paz", "Merlo", "Monte", "Monte Hermoso", "Moreno", "Morón",
    "Navarro", "Necochea", "Nueve de Julio", "Olavarría", "Patagones", "Pehuajó",
    "Pellegrini", "Pergamino", "Pila", "Pilar", "Pinamar", "Presidente Perón",
    "Puán", "Punta Indio", "Quilmes", "Ramallo", "Rauch", "Rivadavia",
    "Rojas", "Roque Pérez", "Saavedra", "Saladillo", "Saliquelló", "San Andrés de Giles",
    "San Antonio de Areco", "San Cayetano", "San Fernando", "San Isidro", "San Miguel",
    "San Nicolás", "San Pedro", "San Vicente", "Suipacha", "Tandil", "Tapalqué",
    "Tigre", "Tordillo", "Tornquist", "Trenque Lauquen", "Tres Arroyos",
    "Tres de Febrero", "Tres Lomas", "Vicente López", "Villa Gesell", "Villarino",
    "Zárate",
  ],
  "Ciudad Autónoma de Buenos Aires": [
    "Agronomía", "Almagro", "Balvanera", "Barracas", "Belgrano", "Boedo",
    "Caballito", "Chacarita", "Coghlan", "Colegiales", "Constitución", "Flores",
    "Floresta", "La Boca", "La Paternal", "Liniers", "Mataderos", "Monte Castro",
    "Montserrat", "Nueva Pompeya", "Núñez", "Palermo", "Parque Avellaneda",
    "Parque Chacabuco", "Parque Chas", "Parque Patricios", "Puerto Madero",
    "Recoleta", "Retiro", "Saavedra", "San Cristóbal", "San Nicolás", "San Telmo",
    "Vélez Sársfield", "Versalles", "Villa Crespo", "Villa del Parque", "Villa Devoto",
    "Villa General Mitre", "Villa Lugano", "Villa Luro", "Villa Ortúzar",
    "Villa Pueyrredón", "Villa Real", "Villa Riachuelo", "Villa Santa Rita",
    "Villa Soldati", "Villa Urquiza",
  ],
  "Catamarca": [
    "Andalgalá", "Antofagasta de la Sierra", "Belén", "Capayán", "El Alto",
    "Fray Mamerto Esquiú", "La Paz", "Paclín", "Pomán", "San Fernando del Valle de Catamarca",
    "Santa María", "Santa Rosa", "Tinogasta", "Valle Viejo",
  ],
  "Chaco": [
    "Charata", "Chorroarín", "Corzuela", "El Sauzalito", "Fontana", "General José de San Martín",
    "La Leonesa", "Las Breñas", "Machagai", "Makallé", "Pampa del Indio",
    "Presidencia de la Plaza", "Presidencia Roque Sáenz Peña", "Puerto Tirol",
    "Quitilipi", "Resistencia", "Samuhu", "Santa Sylvina", "Taco Pozo",
    "Villa Ángela", "Wichi",
  ],
  "Chubut": [
    "Camarones", "Comodoro Rivadavia", "Dolavon", "El Maitén", "Epuyén",
    "Esquel", "Gaiman", "Lago Puelo", "Las Plumas", "Puerto Madryn",
    "Rawson", "Río Mayo", "Río Senguer", "Sarmiento", "Tecka",
    "Trelew", "Trevelin",
  ],
  "Córdoba": [
    "Almafuerte", "Alta Gracia", "Arroyito", "Bell Ville", "Brinkmann",
    "Canals", "Carlos Paz", "Córdoba", "Cosquín", "Cruz del Eje",
    "Dean Funes", "Deán Funes", "Embalse", "Huinca Renancó", "Jesús María",
    "La Carlota", "La Falda", "Laboulaye", "Las Varillas", "Leones",
    "Marcos Juárez", "Mina Clavero", "Morteros", "Oncativo", "Río Ceballos",
    "Río Cuarto", "Río Segundo", "Río Tercero", "Rufino", "Sampacho",
    "San Francisco", "San Marcos Sierras", "Santiago Temple", "Unquillo",
    "Villa Allende", "Villa Carlos Paz", "Villa Cura Brochero", "Villa de María",
    "Villa del Rosario", "Villa Dolores", "Villa María", "Villa Nueva",
    "Villa del Totoral", "Wenceslao Escalante",
  ],
  "Corrientes": [
    "Bella Vista", "Berón de Astrada", "Concepción", "Corrientes", "Curuzú Cuatiá",
    "Empedrado", "Esquina", "Goya", "Itá Ibaté", "Ituzaingó",
    "Lavalle", "Loreto", "Mburucuyá", "Mercedes", "Monte Caseros",
    "Paso de los Libres", "Saladas", "San Cosme", "San Luis del Palmar",
    "San Martín", "San Miguel", "San Roque", "Santa Lucía", "Santo Tomé",
    "Sauce",
  ],
  "Entre Ríos": [
    "Cerrito", "Chajarí", "Colón", "Concordia", "Crespo",
    "Diamante", "Federación", "Federal", "Feliciano", "Gualeguay",
    "Gualeguaychú", "Hasenkamp", "Hernandarias", "La Paz", "Larroque",
    "Lucas González", "Nogoyá", "Paraná", "Rosario del Tala", "San José",
    "San Salvador", "Urdinarrain", "Victoria", "Villaguay",
  ],
  "Formosa": [
    "Clorinda", "El Colorado", "Formosa", "General Enrique Mosconi",
    "Ibarreta", "Ingeniero Juárez", "Las Lomitas", "Pirané",
    "Pozo del Tigre", "Riacho He Hé", "Villa Dos Trece",
  ],
  "Jujuy": [
    "Abra Pampa", "El Carmen", "Humahuaca", "La Quiaca", "Libertador General San Martín",
    "Palpalá", "Perico", "Purmamarca", "San Pedro de Jujuy", "San Salvador de Jujuy",
    "Santa Catalina", "Tilcara", "Tres Cruces", "Volcán",
  ],
  "La Pampa": [
    "Catriló", "Eduardo Castex", "General Acha", "General Pico", "Guatraché",
    "Intendente Alvear", "Jacinto Aráuz", "Macachín", "Quemú Quemú",
    "Realicó", "Santa Isabel", "Santa Rosa", "Toay", "Victorica",
  ],
  "La Rioja": [
    "Aimogasta", "Arauco", "Chamical", "Chilecito", "General Ángel Vicente Peñaloza",
    "La Rioja", "Nonogasta", "Patquía", "Sanagasta", "Tinaco",
    "Ulapes", "Villa Castelli", "Villa Unión",
  ],
  "Mendoza": [
    "Capital (Mendoza)", "General Alvear", "Godoy Cruz", "Guaymallén", "Junín",
    "La Paz", "Las Heras", "Lavalle", "Luján de Cuyo", "Maipú",
    "Malargüe", "Rivadavia", "San Carlos", "San Martín", "San Rafael",
    "Santa Rosa", "Tunuyán", "Tupungato",
  ],
  "Misiones": [
    "Apóstoles", "Aristóbulo del Valle", "Bernardo de Irigoyen", "Campo Grande",
    "Capioví", "Colonia Wanda", "Concepción de la Sierra", "El Dorado",
    "Garuhapé", "General Manuel Belgrano", "Guaraní", "Iguazú", "Itacaruaré",
    "Jardín América", "Leandro N. Alem", "Libertador General San Martín",
    "Montecarlo", "Obera", "Posadas", "Puerto Rico", "San Ignacio",
    "San Javier", "San Pedro", "San Vicente", "Santo Pipó",
  ],
  "Neuquén": [
    "Andacollo", "Barrancas", "Buta Ranquil", "Centenario", "Chos Malal",
    "Cutral Có", "El Cholar", "Junín de los Andes", "Las Lajas", "Loncopué",
    "Neuquén", "Picún Leufú", "Piedra del Águila", "Plaza Huincul",
    "Plottier", "San Martín de los Andes", "San Patricio del Chañar",
    "Villa El Chocón", "Villa La Angostura", "Villa Pehuenia", "Zapala",
  ],
  "Río Negro": [
    "Allen", "Bariloche", "Catriel", "Cervantes", "Chichinales",
    "Choele Choel", "Cinco Saltos", "Cipolletti", "Comallo", "El Bolsón",
    "El Cuy", "General Conesa", "General Enrique Godoy", "General Fernández Oro",
    "General Roca", "Ingeniero Jacobacci", "Lamarque", "Los Menucos",
    "Maquinchao", "Ñorquinco", "Pilcaniyeu", "San Antonio Oeste",
    "San Carlos de Bariloche", "Sierra Colorada", "Sierra Grande", "Valcheta",
    "Viedma", "Villa Regina",
  ],
  "Salta": [
    "Aguaray", "Cafayate", "Campo Quijano", "Cerrillos", "Chicoana",
    "Embarcación", "General Güemes", "Joaquín V. González", "La Caldera",
    "La Candelaria", "Metán", "Orán", "Pichanal", "Rivadavia",
    "Rosario de la Frontera", "Rosario de Lerma", "Salta", "San Antonio de los Cobres",
    "San Ramón de la Nueva Orán", "Santa Victoria Este", "Tartagal",
    "Rosario de Lerma",
  ],
  "San Juan": [
    "Albardón", "Angaco", "Calingasta", "Capital (San Juan)", "Caucete",
    "Chimbas", "Iglesia", "Jachal", "Media Agua", "Pocito",
    "Rawson", "Rivadavia", "San Juan", "Santa Lucía", "Sarmiento",
    "Ullum", "Valle Fértil", "Zonda",
  ],
  "San Luis": [
    "Buena Esperanza", "Justo Daract", "La Toma", "Merlo", "Naschel",
    "Quines", "San Francisco del Monte de Oro", "San Luis", "Santa Rosa del Conlara",
    "Tilisarao", "Villa Mercedes",
  ],
  "Santa Cruz": [
    "Caleta Olivia", "Comandante Luis Piedra Buena", "El Calafate", "El Chaltén",
    "Gobernador Gregores", "Perito Moreno", "Puerto Deseado", "Puerto Madryn",
    "Puerto San Julián", "Río Gallegos", "Río Turbio", "San Julián",
  ],
  "Santa Fe": [
    "Avellaneda", "Cañada de Gómez", "Casilda", "Ceres", "Esperanza",
    "Firmat", "Fray Luis Beltrán", "Gálvez", "Las Rosas", "Las Toscas",
    "Moisés Ville", "Pérez", "Reconquista", "Recreo", "Rafaela",
    "Rosario", "Rufino", "San Jorge", "San Javier", "San Justo",
    "Santa Fe", "Santo Tomé", "Sastre", "Sunchales", "Tostado",
    "Venado Tuerto", "Vera", "Villa Cañás", "Villa Constitución",
    "Villa del Rosario", "Villa Gobernador Gálvez", "Villa Ocampo",
    "Wheelwright",
  ],
  "Santiago del Estero": [
    "Añatuya", "Bandera", "Beltrán", "Campo Gallo", "Clodomira",
    "Fernández", "Frías", "La Banda", "Loreto", "Monte Quemado",
    "Nueva Esperanza", "Quimilí", "Real Sayana", "Recuperación",
    "Ojo de Agua", "Sumampa", "Suncho Corral", "Termas de Río Hondo",
    "Santiago del Estero", "Pinto", "Pozo Hondo",
  ],
  "Tierra del Fuego": [
    "Río Grande", "Tolhuin", "Ushuaia",
  ],
  "Tucumán": [
    "Aguilares", "Alberdi", "Banda del Río Salí", "Bella Vista", "Burruyacú",
    "Chicligasta", "Concepción", "El Cadillal", "Famaillá", "Juan Bautista Alberdi",
    "La Cocha", "Leales", "Lules", "Monteros", "San Miguel de Tucumán",
    "Simoca", "Tafí del Valle", "Tafí Viejo", "Trancas", "Yerba Buena",
  ],
};
