export const PROVINCIAS = [
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Ciudad Autónoma de Buenos Aires",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
] as const;

export type Provincia = (typeof PROVINCIAS)[number];

export const LOCALIDADES: Record<Provincia, string[]> = {
  "Buenos Aires": [
    "Almirante Brown", "Avellaneda", "Azul", "Bahía Blanca", "Balcarce",
    "Berazategui", "Berisso", "Brandsen", "Bragado", "Campana",
    "Cañuelas", "Chivilcoy", "Coronel Suárez", "Ensenada", "Escobar",
    "Esteban Echeverría", "Ezeiza", "Florencio Varela", "General Pueyrredón (Mar del Plata)",
    "General San Martín", "General Rodríguez", "Hurlingham", "Ituzaingó",
    "José C. Paz", "La Matanza", "La Plata", "Lanús", "Lomas de Zamora",
    "Luján", "Malvinas Argentinas", "Marcos Paz", "Mercedes", "Merlo",
    "Moreno", "Morón", "Necochea", "Olavarría", "Pergamino",
    "Pilar", "Quilmes", "Ramallo", "Roque Pérez", "Saladillo",
    "San Fernando", "San Isidro", "San Miguel", "San Nicolás de los Arroyos",
    "San Pedro", "Tandil", "Tigre", "Tres de Febrero", "Tres Arroyos",
    "Vicente López", "Zárate",
  ],
  "Catamarca": [
    "Andalgalá", "Belén", "Catamarca", "Fiambalá", "Frías",
    "Huillapima", "Londres", "Recreo", "Santa María", "Tinogasta",
  ],
  "Chaco": [
    "Charata", "Fontana", "General José de San Martín", "Juan José Castelli",
    "La Leonesa", "Las Breñas", "Makallé", "Presidencia Roque Sáenz Peña",
    "Puerto Tirol", "Quitilipi", "Resistencia", "Sáenz Peña", "Villa Ángela",
  ],
  "Chubut": [
    "Comodoro Rivadavia", "Esquel", "Madryn (Puerto Madryn)", "Puerto Madryn",
    "Rawson", "Trelew", "Rada Tilly", "Río Mayo", "Sarmiento",
  ],
  "Ciudad Autónoma de Buenos Aires": [
    "Agronomía", "Almagro", "Balvanera", "Barracas", "Belgrano",
    "Boedo", "Caballito", "Chacarita", "Coghlan", "Colegiales",
    "Constitución", "Flores", "Floresta", "La Boca", "La Paternal",
    "Liniers", "Mataderos", "Monte Castro", "Montserrat", "Nueva Pompeya",
    "Núñez", "Palermo", "Parque Avellaneda", "Parque Chacabuco",
    "Parque Chas", "Parque Patricios", "Puerto Madero", "Recoleta",
    "Retiro", "Saavedra", "San Cristóbal", "San Nicolás", "San Telmo",
    "Versalles", "Villa Crespo", "Villa del Parque", "Villa Devoto",
    "Villa General Mitre", "Villa Lugano", "Villa Luro", "Villa Ortúzar",
    "Villa Pueyrredón", "Villa Real", "Villa Riachuelo", "Villa Santa Rita",
    "Villa Soldati", "Villa Urquiza",
  ],
  "Córdoba": [
    "Alta Gracia", "Arroyito", "Bell Ville", "Berrotarán", "Brinkmann",
    "Córdoba", "Cruz del Eje", "Dean Funes", "Jesús María", "La Calera",
    "Laboulaye", "Marcos Juárez", "Morteros", "Oncativo", "Río Cuarto",
    "Río Tercero", "San Francisco", "Unquillo", "Villa Carlos Paz",
    "Villa Dolores", "Villa María", "Villa Nueva",
  ],
  "Corrientes": [
    "Bella Vista", "Bonpland", "Corrientes", "Curuzú Cuatiá", "Goya",
    "Ituzaingó", "Libres (Paso de los Libres)", "Mercedes", "Monte Caseros",
    "Paso de los Libres", "Saladas", "Santo Tomé",
  ],
  "Entre Ríos": [
    "Basavilbaso", "Chajarí", "Colón", "Concepción del Uruguay", "Concordia",
    "Diamante", "Federal", "Federación", "Gualeguay", "Gualeguaychú",
    "La Paz", "Nogoyá", "Paraná", "Rosario del Tala", "San José",
    "Urdinarrain", "Victoria", "Villaguay",
  ],
  "Formosa": [
    "Clorinda", "El Colorado", "Fontana", "Formosa", "General Lucio Victorio Mansilla",
    "Ingeniero Juárez", "Laguna Blanca", "Las Lomitas", "Pirané",
  ],
  "Jujuy": [
    "El Carmen", "Humahuaca", "La Quiaca", "Ledesma (Libertador General San Martín)",
    "Libertador General San Martín", "Palpalá", "Perico", "San Pedro de Jujuy",
    "San Salvador de Jujuy", "Tilcara", "Volcán",
  ],
  "La Pampa": [
    "Eduardo Castex", "General Acha", "General Pico", "Guatraché",
    "Intendente Alvear", "Macachín", "Realicó", "Santa Rosa", "Toay",
  ],
  "La Rioja": [
    "Aimogasta", "Chamical", "Chilecito", "La Rioja", "Patquía",
    "Tinogasta", "Villa Unión", "Vinchina",
  ],
  "Mendoza": [
    "General Alvear", "Godoy Cruz", "Guaymallén", "Junín", "La Paz",
    "Las Heras", "Lavalle", "Luján de Cuyo", "Maipú", "Malargüe",
    "Mendoza", "Rivadavia", "San Martín", "San Rafael", "Santa Rosa",
    "Tunuyán", "Tupungato",
  ],
  "Misiones": [
    "Apóstoles", "Alem (Leandro N. Alem)", "Aristóbulo del Valle",
    "Bernardo de Irigoyen", "Campo Grande", "Dos de Mayo",
    "El Dorado", "Garupá", "Iguazú (Puerto Iguazú)", "Jardín América",
    "Leandro N. Alem", "Montecarlo", "Oberá", "Posadas", "Puerto Iguazú",
    "Puerto Rico", "San Vicente",
  ],
  "Neuquén": [
    "Centenario", "Chos Malal", "Cutral Có", "Junín de los Andes",
    "Neuquén", "Plaza Huincul", "San Martín de los Andes",
    "Villa La Angostura", "Zapala",
  ],
  "Río Negro": [
    "Allen", "Bariloche (San Carlos de Bariloche)", "Catriel", "Cervantes",
    "Chichinales", "Cinco Saltos", "Cipoletti", "El Bolsón", "General Roca",
    "Ingeniero Luis A. Huergo", "Jacobacci", "Luis Beltrán", "Roca",
    "San Antonio Oeste", "San Carlos de Bariloche", "Viedma",
  ],
  "Salta": [
    "Cafayate", "Cerrillos", "Embarcación", "General Güemes",
    "Joaquín V. González", "Metán", "Orán", "Rosario de la Frontera",
    "Rosario de Lerma", "Salta", "San Ramón de la Nueva Orán",
    "Tartagal",
  ],
  "San Juan": [
    "Caucete", "Chimbas", "Pocito", "Rawson", "Rivadavia", "San Juan",
    "Santa Lucía", "Ullum", "Zonda",
  ],
  "San Luis": [
    "Merlo", "San Luis", "Villa Mercedes", "Justo Daract", "La Toma",
    "Quines", "Río Cuarto (límite)", "Tilisarao",
  ],
  "Santa Cruz": [
    "Caleta Olivia", "El Calafate", "Gobernador Gregores", "Las Heras",
    "Perito Moreno", "Puerto Deseado", "Puerto Madryn", "Puerto Santa Cruz",
    "Río Gallegos", "Río Turbio",
  ],
  "Santa Fe": [
    "Avellaneda", "Cañada de Gómez", "Casilda", "Capitán Bermúdez",
    "El Trébol", "Esperanza", "Firmat", "Fray Luis Beltrán", "Granadero Baigorria",
    "Las Rosas", "Pérez", "Reconquista", "Rafaela", "Recreo",
    "Rosario", "Rufino", "San Jorge", "Santa Fe", "Santo Tomé",
    "Venado Tuerto", "Villa Constitución", "Villa Gobernador Gálvez",
  ],
  "Santiago del Estero": [
    "Añatuya", "Beltrán", "Clodomira", "Fernández", "Frías",
    "La Banda", "Loreto", "Monte Quemado", "Quimilí", "Río Hondo (Termas de Río Hondo)",
    "Santiago del Estero", "Termas de Río Hondo",
  ],
  "Tierra del Fuego": [
    "Río Grande", "Tolhuin", "Ushuaia",
  ],
  "Tucumán": [
    "Aguilares", "Alderetes", "Banda del Río Salí", "Bella Vista",
    "Concepción", "El Cadillal", "Famaillá", "Juan Bautista Alberdi",
    "Monteros", "San Miguel de Tucumán", "Simoca", "Tafí del Valle",
    "Tafí Viejo", "Yerba Buena",
  ],
};
